### ISSUE TITLE
Azure DevOps pipeline conditions for plan.yml, epac-dev-pipeline.yml & epac-tenant-pipeline.yml

### ISSUE THREAD

**Issue by stateofthearb** [Azure/enterprise-azure-policy-as-code#1063]
**Describe the bug**
The official EPAC Azure DevOps pipeline templates in StarterKit have critical issues with stage dependencies and output variable handling, causing Deploy stages to be incorrectly skipped even when policy changes are detected. The templates use incorrect variable syntax mixing task-scoped variables with cross-stage output variables, and use invalid dependency references that don't work in Azure DevOps.

**To Reproduce**
Use the official EPAC pipeline templates from StarterKit/Pipelines/AzureDevOps/templates-ps1-module/
Set up a pipeline with Plan and Deploy stages following the template pattern
Make policy changes that should trigger deployment
Run the pipeline and observe that Build-DeploymentPlans detects changes (artifact is published)
Deploy stage is skipped despite changes being detected
Check pipeline logs - no ##vso[task.setvariable...] output variables are set by EPAC

**Expected behavior**
When Build-DeploymentPlans detects policy or role changes, the Deploy stage should run automatically. The pipeline should use proper Azure DevOps variable scoping and dependency syntax for reliable stage-to-stage communication.

**Screenshots**

<img width="519" height="354" alt="Image" src="https://github.com/user-attachments/assets/b93f3960-39e0-45d8-b27d-93706148020c" />

**EPAC Version**
Latest version from PowerShell Gallery (EnterprisePolicyAsCode module)

Issues Identified:

Missing Output Variable Declarations: The plan template doesn't explicitly declare output variables in the job definition, which is required for cross-stage communication in Azure DevOps.

Incorrect Variable Syntax:

The publish step uses variables['Plan.deployPolicyChanges'] (task-scoped variables)
The deploy condition uses dependencies.Plan.outputs['Plan.Plan.deployPolicyChanges'] (cross-stage output variables)
These reference different variable scopes - EPAC sets task variables but doesn't create output variables
Invalid Dependency Syntax:

The deploy stage condition uses dependencies which is only available within the same stage
Should use stageDependencies for stage-to-stage communication
However, stageDependencies don't work reliably in stage-level conditions, only job-level conditions

Current Problematic Code:
# In deploy pipeline condition:
condition: and(not(failed()), not(canceled()), or(eq(dependencies.Plan.outputs['Plan.Plan.deployPolicyChanges'], 'yes'), eq(dependencies.Plan.outputs['Plan.Plan.deployRoleChanges'], 'yes')))

# In plan template publish step:
condition: and(succeeded(), or(eq(variables['Plan.deployPolicyChanges'], 'yes'), eq(variables['Plan.deployRoleChanges'], 'yes')))

Suggested Fix: The Build-DeploymentPlans command should set proper Azure DevOps output variables:
Build-DeploymentPlans -PacEnvironmentSelector ${{ parameters.pacEnvironmentSelector }} -DevOpsType "ado"

# Set output variables for cross-stage communication
Write-Host "##vso[task.setvariable variable=deployPolicyChanges;isOutput=true]$deployPolicyChanges"
Write-Host "##vso[task.setvariable variable=deployRoleChanges;isOutput=true]$deployRoleChanges"

The stage conditions needs to be moved to the job as stage dependency variables only work on jobs not stages. This also needs to change from dependencies to stageDependencies to work across stages.

Or alternatively, simplify the conditions to just check if the Plan stage succeeded, since the artifact publishing already validates that changes exist.

Additional Context This affects anyone using the official StarterKit templates and causes confusion when deployment stages are unexpectedly skipped despite having policy changes to deploy.

**Comment by apybar** [comment]
I've updated the starter-kit yaml files to be like this:

<img width="1664" height="1631" alt="Image" src="https://github.com/user-attachments/assets/805b5add-7015-455f-a35e-d0a4f96fb01a" />

I believe this should fix some unwanted skips @stateofthearb

**Comment by apybar** [comment]
I believe this should solve the problem but feel free to correct me otherwise and reopen the ticket please @stateofthearb

**Comment by stateofthearb** [comment]
@apybar Thank you for the feedback, I also ended up stripping the stage dependencies to get it working quickly. Just to add you still have a stage dependency in the condition but its not declared in the plan file from what I can see.

    variables:
      localDeployPolicyChanges: $[stageDependencies.Plan.Plan.outputs['Plan.deployPolicyChanges']]
      localDeployRoleChanges: $[stageDependencies.Plan.Plan.outputs['Plan.deployRoleChanges']]

https://github.com/Azure/enterprise-azure-policy-as-code/blob/main/StarterKit/Pipelines/AzureDevOps/templates-ps1-module/plan.yml

Would need to be declared in the plan template, something like this.
Set output variables for cross-stage communication
Write-Host "##vso[task.setvariable variable=deployPolicyChanges;isOutput=true]$deployPolicyChanges"
Write-Host "##vso[task.setvariable variable=deployRoleChanges;isOutput=true]$deployRoleChanges"
