### ISSUE TITLE
Issues with removing Policy exemption etc

### ISSUE THREAD

**Issue by mavericksurfer** [Azure/enterprise-azure-policy-as-code#224]
Hi Guys,

Couple of issues I noticed during my testing:

1. I'm having trouble removing policy exemption(s) after creation. Even when I remove the exemption from the CSV file, it doesn't get removed from Azure.

2. If you want to update a policy/initiative with modify/DINE effect after deployment, such as its policy definition or exemption, it would throw out an error during the "Deploy role assignment" stage of the pipeline. However, the updates actually work. Perhaps a condition should be added before executing New-AzRoleAssignment command.
 
New-AzRoleAssignment: /home/vsts/work/1/s/Scripts/Deploy/Deploy-RolesPlan.ps1:92
Line |
  92 |  …   $result = New-AzRoleAssignment @splat -WarningAction SilentlyContin …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Operation returned an invalid status code 'Conflict'

**Comment by anwather** [comment]
Created issue #225 for point 2

**Comment by anwather** [comment]
Fixed in release v7.1.8

**Comment by mavericksurfer** [comment]
@anwather, thanks for the quick response.
I can confirm that removal of exemptions at subscription and resource group level are working now, however I still can't seem to remove the exemptions set at the management group level.

**Comment by anwather** [comment]
I'm unable to replicate this - can you please provide steps - below is what I did.

1.  Assign an exemption at a management group scope - deploy
2.  Rename the exemption file to .bak - deploy. The exemption was removed.

**Comment by anwather** [comment]
@mavericksurfer - Can you also provide repro steps for #225 - below is what I did.

1. Created a custom policy definition and assignment - deployed policy def, assignment and it was a modify policy so RBAC was created.
2. Changed a parameter name in the definition and redployed. It removed and replaced the definition and assignment. Running Deploy-RolesPlan deployed a new identity and correctly removed the old one.

**Comment by mavericksurfer** [comment]
@anwather, sorry for not getting back to you sooner. 
I have just tested again and can confirm that both issues are fixed now, much appreciated.
