### ISSUE TITLE
AzureUSGovernment "add role Unknown"

### ISSUE THREAD

**Issue by glsutter** [Azure/enterprise-azure-policy-as-code#513]
When creating plans using EPAC in an AzureUSGovernment tenant, we're getting a lot of messages like:
add role Unknown at /managementGroups/TEST1-decommissioned

And in the roles-plan.json, we see entries like:
`{
        "principalId": null,
        "scope": "/providers/Microsoft.Management/managementGroups/TEST1-decommissioned",
        "assignmentId": "/providers/Microsoft.Management/managementGroups/TEST1-decommissioned/providers/Microsoft.Authorization/policyAssignments/decomm-guardrails",
        "displayName": "Enforce ALZ Decommissioned Guardrails",
        "objectType": "ServicePrincipal",
        "roleDisplayName": "Unknown",
        "roleDefinitionId": "/providers/microsoft.authorization/roleDefinitions/9980e02c-c2be-4d73-94e8-173b1dc7cf3c"
      },`

This doesn't seem correct. The RoleDefinitionId is for the "Virtual Machine Contributor" role. 

We suspect this is a government tenant issue, since the problem is not appearing in our commercial tenant. 

Any suggestions on how to debug/isolate the problem? We couldn't find the relevant PowerShell code in EPAC. 

Thanks

**Comment by techlake** [comment]
Thank you for telling us about this. Can you check if the following queries resolve in Az Gov Cloud:
- authorizationresources | where type == `"microsoft.authorization/roleassignments`"
- authorizationresources | where type == "microsoft.authorization/roledefinitions"

We have a fix for China cloud where that table doesn't exist. I can add that to the impending release if you confirm that the second query fails.

**Comment by glsutter** [comment]
Both of those queries fail in AzureUSGovernment with the message:
Table authorizationresources is invalid, unsupported or disallowed. (Code:DisallowedLogicalTableName)

**Comment by glsutter** [comment]
Could you provide a patch or new PowerShell files for us to deploy temporarily before the next release? This is a blocker for one of our policy releases? Thanks.

**Comment by glsutter** [comment]
My PL asked an important question - Does this issue cause any functional issues with deployment? Or is simply a role display name issue? If it's functional as is, and will not cause later problems, then we want to go ahead and deploy. Thanks.

**Comment by techlake** [comment]
No, however, I'll have this fixed soon.

**Comment by techlake** [comment]
Can you try one more query for me, please?

PolicyResources | where type == 'microsoft.authorization/policyexemptions'

**Comment by techlake** [comment]
I already implemented the change for Roles

**Comment by glsutter** [comment]
Thanks! 

The PolicyResources | where type == 'microsoft.authorization/policyexemptions' query in AzureUSGovernment did not fail. But we have no exemptions in that tenant:

No results.

**Comment by glsutter** [comment]
Just updated code from latest main branch. But the "add role Unknown" is still showing in the output of Build-DeploymentPlans.ps1. Also getting some new DisallowedLogicalTableName errors:

`Search-AzGraph: /builds/xcloud/xcloud-monorepo/azure/mag/elz/epac/Scripts/Helpers/Search-AzGraphAllItems.ps1:10
Line |
  10 |      $result = Search-AzGraph $Query -First 1000 @scope
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | {   "error": {     "code": "BadRequest",     "message":
     | "Please provide below info when asking for support: timestamp
     | = 2024-03-29T12:43:17.5627219Z, correlationId =
     | ec0b4b50-c421-4739-9feb-6557b86dab26.",     "details": [      
     | {         "code": "DisallowedLogicalTableName",        
     | "message": "Table authorizationresources is invalid,
     | unsupported or disallowed."       }     ]   } }
MethodInvocationException: /builds/xcloud/xcloud-monorepo/azure/mag/elz/epac/Scripts/Helpers/Search-AzGraphAllItems.ps1:11
Line |
  11 |      $null = $data.AddRange($result.Data)
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exception calling "AddRange" with "1" argument(s): "Collection
     | cannot be null. (Parameter 'c')"
Search-AzGraph: /builds/xcloud/xcloud-monorepo/azure/mag/elz/epac/Scripts/Helpers/Search-AzGraphAllItems.ps1:10
Line |
  10 |      $result = Search-AzGraph $Query -First 1000 @scope
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | {   "error": {     "code": "BadRequest",     "message":
     | "Please provide below info when asking for support: timestamp
     | = 2024-03-29T12:43:18.0439564Z, correlationId =
     | d4d0bcf8-2a01-447a-bc16-652835e16dcc.",     "details": [      
     | {         "code": "DisallowedLogicalTableName",        
     | "message": "Table authorizationresources is invalid,
     | unsupported or disallowed."       }     ]   } }`

**Comment by techlake** [comment]
Fixed in v10.0.0 released on 4/5/2024
